volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  default:
    name: kafka-spark-network
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9999:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  # image: grafana/grafana:latest
  # container_name: grafana
  # ports:
  #   - "3000:3000"
  # depends_on:
  #   - prometheus
